MODNAME = khello
include $(src)/../Makefile.khook

obj-m           += $(MODNAME).o
$(MODNAME)-y    += main.o $(ORIG_BPF_OBJ) nil_verifier.o $(KHOOK_GOALS)
ccflags-y       += $(KHOOK_CCFLAGS) -Wno-unused-function -Wno-attributes
ldflags-y       += $(KHOOK_LDFLAGS)
